//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: bwmod
// Function header: bwmodFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createbwmodFunctionMap();

extern "C"  {


	xsccCall     gausabs;
	xsccCall     agausabs;
	xsccCall     newhcut;
	xsccCall     xscompmag2;
	xsccCall     tbnew;
	xsccCall     tbvabsfeo;
	xsccCall     tbgas;
	xsccCall     tbvabspcf;
	xsccCall     tbvabsrel;
	XSCCall      grbcutoffPowerLaw;
}


#endif
