//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: bwmod
// Function body: bwmodFunctionMap.cxx

#include    "bwmodFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>

void 
createbwmodFunctionMap()
{


	XSFunctionMap["gausabs"]  = new XSCall<xsccCall>(gausabs);
	XSFunctionMap["agausabs"] = new XSCall<xsccCall>(agausabs);
	XSFunctionMap["newhcut"]  = new XSCall<xsccCall>(newhcut);
	XSFunctionMap["compmag2"] = new XSCall<xsccCall>(xscompmag2);
	XSFunctionMap["tbnew"]    = new XSCall<xsccCall>(tbnew);
	XSFunctionMap["tbnew_feo"] = new XSCall<xsccCall>(tbvabsfeo);
	XSFunctionMap["tbnew_gas"] = new XSCall<xsccCall>(tbgas);
	XSFunctionMap["tbnew_pcf"] = new XSCall<xsccCall>(tbvabspcf);
	XSFunctionMap["tbnew_rel"] = new XSCall<xsccCall>(tbvabsrel);
	XSFunctionMap["grbcut"]   = new XSCall<XSCCall>(grbcutoffPowerLaw);

}
