//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: bwmod Created :
// Initializer: bwmod.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "bwmodFunctionMap.h"
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Bwmod_Init(Tcl_Interp* tclInterp);
extern "C" int Bwmod_SafeInit(Tcl_Interp* tclInterp);

int Bwmod_Init(Tcl_Interp* tclInterp)
{
        return Bwmod_SafeInit(tclInterp);
}

int Bwmod_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "bwmod";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createbwmodFunctionMap();
        XSModelFunction::updateComponentList
              ("/home/jovyan/work/ap-lab-i-2022/xspec_lmod/model.dat");
        return TCL_OK;

}

